# Results

```{r message=FALSE, warning=FALSE, include=FALSE}
library(readr)
df <- read_csv("C:/Users/chaoy/Desktop/Fall2021/5702_EDAV/finalproject_data/cash_information_clean.csv")

df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], as.factor)
```

## When
```{r include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(vcd)
library(patchwork)
```

### Time in Day
```{r fig.width=8, message=FALSE, warning=FALSE, echo=FALSE}
df_time <- df %>% select(Time, Year) %>%
  mutate(hour = hour(Time)) %>%
  group_by(hour, Year) %>%
  summarize(n = n()) %>%
  ungroup()

ggplot(df_time, aes(hour,n, fill=factor(Year))) + 
  geom_bar(stat="identity", position=position_dodge()) + 
  scale_fill_brewer(palette="Set2") +
  theme_minimal()
```
```{r fig.height=15, fig.width=20}
df_time_reason<- df %>% 
  mutate(time_hour = hour(Time)) %>%
 #  filter(time_hour==0 | time_hour==8 | time_hour==17) %>% 
  mutate(time_hour = factor(time_hour), 
         `Lighting Conditions` = ifelse(str_detect(`Lighting Conditions`, "Dark-Road"), 
                                        sub("^\\S+\\s+","", `Lighting Conditions`), as.character(`Lighting Conditions`)), 
          `Road Descriptor`= abbreviate(`Road Descriptor`, 1, named = FALSE), 
         `Traffic Control Device`= abbreviate(`Traffic Control Device`, 1, named = FALSE)) %>%
  select(time_hour, `Crash Descriptor`, `Lighting Conditions`, `Road Descriptor`, `Traffic Control Device`, Collision_Detail, `Collision Type Descriptor`)

pairs(table(df_time_reason), highlighting=2)
```


```{r fig.width=10, message=FALSE, warning=FALSE, echo=FALSE}
p1<- df_time_reason %>% 
  filter(time_hour==0) %>%
  group_by(time_hour, `Lighting Conditions`) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  ggplot(aes(x=fct_relevel(factor(`Lighting Conditions`), "Unknown", after=Inf), y=n)) + 
  geom_col()+ 
  labs(x="", y="") + ylim(0, 50000)
  
p2<- df_time_reason %>%
filter(time_hour==8) %>%
group_by(time_hour, `Lighting Conditions`) %>%
summarise(n=n()) %>%
ungroup() %>%
ggplot(aes(x=fct_relevel(factor(`Lighting Conditions`), "Unknown", after=Inf), y=n)) +
geom_col()+ 
  labs(x="", y="")  + ylim(0, 50000)

p3 <- df_time_reason %>%
filter(time_hour==17) %>%
group_by(time_hour, `Lighting Conditions`) %>%
summarise(n=n()) %>%
  ungroup() %>%
ggplot(aes(x=fct_relevel(factor(`Lighting Conditions`), "Unknown", after=Inf), y=n)) +
geom_col()+ 
  labs(x="", y="") + ylim(0, 50000)


p4<- df_time_reason %>% 
  filter(time_hour==0) %>%
  group_by(time_hour, `Road Descriptor`) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  ggplot(aes(x=factor(`Road Descriptor`), y=n)) + 
  geom_col()+ 
  labs(x="", y="")+ ylim(0, 58000)
  
p5<- df_time_reason %>%
filter(time_hour==8) %>%
group_by(time_hour, `Road Descriptor`) %>%
summarise(n=n()) %>%
ungroup() %>%
ggplot(aes(x=factor(`Road Descriptor`), y=n)) +
geom_col()+ 
  labs(x="", y="")+ ylim(0, 58000)

p6 <- df_time_reason %>%
filter(time_hour==17) %>%
group_by(time_hour, `Road Descriptor`) %>%
summarise(n=n()) %>%
  ungroup() %>%
ggplot(aes(x=factor(`Road Descriptor`), y=n)) +
geom_col()+ 
  labs(x="", y="") + ylim(0, 58000)

wrap_plots(p1, p2, p3, p4, p5, p6)
```
```{r fig.width=10, message=FALSE, warning=FALSE, echo=FALSE}
p7<- df_time_reason %>% 
  filter(time_hour==0, `Traffic Control Device` != "N") %>%
  group_by(time_hour, `Traffic Control Device`) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  ggplot(aes(x=factor(`Traffic Control Device`), y=n)) + 
  geom_col()+ 
  labs(x="", y="")+ ylim(0, 20000)
  
p8<- df_time_reason %>%
filter(time_hour==8, `Traffic Control Device` != "N") %>%
group_by(time_hour, `Traffic Control Device`) %>%
summarise(n=n()) %>%
ungroup() %>%
ggplot(aes(x=factor(`Traffic Control Device`), y=n)) +
geom_col()+ 
  labs(x="", y="")+ ylim(0, 20000)

p9 <- df_time_reason %>%
filter(time_hour==17, `Traffic Control Device` != "N") %>%
group_by(time_hour, `Traffic Control Device`) %>%
summarise(n=n()) %>%
  ungroup() %>%
ggplot(aes(x=factor(`Traffic Control Device`), y=n)) +
geom_col()+ 
  labs(x="", y="") + ylim(0, 20000)

wrap_plots(p7, p8, p9)
```
```{r fig.width=10, message=FALSE, warning=FALSE, echo=FALSE}
p10<- df_time_reason %>% 
  filter(time_hour==0) %>%
  group_by(time_hour, `Collision Type Descriptor`) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  ggplot(aes(x=factor(`Collision Type Descriptor`), y=n)) + 
  geom_col()+ 
  labs(x="", y="")+ ylim(0, 25000)
  
p11<- df_time_reason %>%
filter(time_hour==8) %>%
group_by(time_hour, `Collision Type Descriptor`) %>%
summarise(n=n()) %>%
ungroup() %>%
ggplot(aes(x=factor(`Collision Type Descriptor`), y=n)) +
geom_col()+ 
  labs(x="", y="")+ ylim(0, 25000)

p12<- df_time_reason %>%
filter(time_hour==17) %>%
group_by(time_hour, `Collision Type Descriptor`) %>%
summarise(n=n()) %>%
  ungroup() %>%
ggplot(aes(x=factor(`Collision Type Descriptor`), y=n)) +
geom_col()+ 
  labs(x="", y="") + ylim(0, 25000)

wrap_plots(p10, p11, p12)
```

### Day of Week
```{r fig.width=8, message=FALSE, warning=FALSE, echo=FALSE}
df %>%
  select(`Day of Week`, Year) %>%
  group_by(`Day of Week`, Year) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  
ggplot(aes(fct_relevel(`Day of Week`, "Monday", "Tuesday", "Wednesday","Thursday", "Friday", "Saturday", "Sunday"),n,  fill=factor(Year))) +
  geom_bar(stat="identity", position=position_dodge()) + 
  scale_fill_brewer(palette="Set2") +
  labs(x="Day of Week", y="Frequency") +
  theme_minimal()
```

### Month of Year
```{r fig.width=8, message=FALSE, warning=FALSE, echo=FALSE}
df %>% select(Date) %>%
  mutate(Month = month(Date)) %>%
  group_by(Month) %>%
  summarize(n = n()) %>%

ggplot(aes(factor(Month),n)) + 
  geom_col(fill="#2470b9") +
  labs(x="Month", y="Frequency") +
  theme_minimal()
```


## Where
```{r echo=FALSE, fig.height=10, fig.width=20, message=FALSE, warning=FALSE}
ny_county <- subset(map_data("county"), region == "new york") 
  
df_county <- right_join(df %>% 
                         group_by(`County Name`) %>%
                         summarise(n=n()) %>%
                         mutate(subregion = sub("\\.", "",tolower(`County Name`))) %>%
                         select(subregion, n), 
                       ny_county, 
                       by = "subregion") %>%
  select(subregion, n, long, lat, group) %>%
  drop_na()

lower_state <- df_county %>% 
  filter(n>50000) %>% 
  group_by(subregion) %>% 
  summarise(long=mean(long), lat=mean(lat))

embed_plot <- df_county %>% 
  filter(n>50000) %>%
ggplot(aes(x=long, y=lat)) +
  geom_polygon(aes(group = group, fill=n), color = "grey") +
  with(lower_state, annotate(geom="text", x = long, y = lat,
                             label=subregion, size=2)) +
  labs(title = "Long Island Details", x = "longitude", y = "latitude") +
  scale_fill_gradient(low="white", high="darkgreen") +
  theme(panel.background = element_blank()) 

ny_county_distinct <- ny_county %>% 
  group_by(subregion) %>% 
  summarise(long=mean(long), lat=mean(lat))

ggplot(data=df_county, aes(x=long, y=lat)) +
  geom_polygon(aes(group = group, fill=n), color = "grey") +
  with(ny_county_distinct, annotate(geom="text", x = long, y = lat, 
                                    label=subregion, size=3)) +
  labs(title = "New York State Crash by Counties", x = "longitude", y = "latitude") +
  scale_fill_gradient(low="white", high="darkgreen") +
  theme(panel.background = element_blank(), plot.title = element_text(hjust = 0.5)) +
  inset_element(embed_plot,0.01, 0.01, 0.35, 0.35)
```

